language: python
python:
- '3.6'

before_install:
- openssl aes-256-cbc -K $encrypted_7462d68a9e03_key -iv $encrypted_7462d68a9e03_iv
  -in data/contacts.csv.enc -out data/contacts.csv -d

jobs:
  include:
  - stage: build_pages
    python: '3.6'
    script:
    - python3 paper-extractor.py && python3 preprint-extractor.py
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      keep_history: true
      on:
        branch: master
