name: extract-papers

on:
  schedule:
  # Run at 00:30 every day
    - cron:  '30 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  extract-papers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Extract HDR UK Papers
        run: python3 paper-extractor.py
      - name: Commit extracts to master branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit new papers
          branch: ${{ github.head_ref }}
          commit_user_name: Susheel Varma
          commit_user_email: susheel.varma@hdruk.ac.uk
          commit_author: Susheel Varma <susheel.varma@hdruk.ac.uk>
      - name: Commit extracts to gh-pages branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit new papers
          branch: gh-pages
          commit_user_name: Susheel Varma
          commit_user_email: susheel.varma@hdruk.ac.uk
          commit_author: Susheel Varma <susheel.varma@hdruk.ac.uk>
